/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.seqera.genepi;

public class Application {

    public static void main(String[] args) {
        System.out.println("do nothing");
    }
}
